export const projects = [
  {
    title: 'Airbnb Clone ',
    description: "Using Next.js, Prisma and Tailwind I build a full airbnb clone with reservations, bookings and Google Authentication ",
      image: '/images/6.png',
      tags: ['Next.js', 'Prisma', 'Tailwind'],
    visit: 'https://github.com/FranBaca/Airbnb-clone-',
    id: 7,
  },
  {
    title: 'Latam Wallet ',
    description: "As a team of developers and designers we build a MVP for a Wallet of cryptocurrency, with transfers between users, withdrawals etc. Using React, Node, Express, MongoDB",
      image: '/images/5.png',
      tags: ['Cloud', 'Express', 'React', 'Node'],
    source: 'https://latam-wallet-deploy.vercel.app/',
    visit: 'https://github.com/FranBaca/LatamWalletDeploy',
    id: 6,
  }, 
  {
    title: 'Henry Hotel',
    description: "Using React, Node.js, Express & Cloud database, my team and I build a full app for a hotel with check-ins, reservation system, event planning, and admin panel",
      image: '/images/1.png',
      tags: ['Cloud', 'Express', 'React', 'Node'],
    source: 'https://henryhotel.hruiz.com/',
    visit: 'https://github.com/FranBaca/ecommerce-FT10-G2',
    id: 0,
  },
  {
    title: 'Henry Hotel',
    description: "Using React, Node.js, Express & Cloud database, my team and I build a full app for a hotel with check-ins, reservation system, event planning, and admin panel",
      image: '/images/1.png',
      tags: ['Cloud', 'Express', 'React', 'Node'],
    source: 'https://henryhotel.hruiz.com/',
    visit: 'https://github.com/FranBaca/ecommerce-FT10-G2',
    id: 0,
  },
  {
    title: 'Liteflix',
    description: "A lightweight netflix clone created with React, Chakra UI, React Dropzone",
    image: '/images/2.png',
    tags: ['React', 'Node', 'Chakra UI'],
    source: 'https://liteflix-two.vercel.app/',
    visit: 'https://github.com/FranBaca/Liteflix',
    id: 1,
  },
  {
    title: 'Rick & Morty App',
    description: "A simple web app to display information about all Rick & Morty's series characters",
      image: '/images/3.jpg',
      tags: ['React', 'JavaScript','Node','API REST'],
    source: 'https://rick-nm-orty-app-deploy.vercel.app/',
    visit: 'https://github.com/FranBaca/RickNMortyApp',
    id: 2,
  },
  {
    title: 'Crypto Tracker',
    description: "This is a Web App, connected to API REST that tracks all active cryptocurrencies, displays his values, and data charts",
    image: '/images/4.png',
    tags: ['React', 'API REST', 'Material-UI'],
    source: 'https://crypto-react-app-rho.vercel.app/',
    visit: 'https://github.com/FranBaca/Crypto-React-App',
    id: 3,
  },

  {
    title: 'Chat App - Socket IO',
    description: "This is a real-time chat application built using React, Node.js and Express. The aim of this project is to provide users with a simple, yet effective platform to communicate with each other in real-time.",
    image: '/assets/chat.png',
    tags: ['React', 'Socket IO', 'Node', 'Express'],
    visit: 'https://github.com/FranBaca/Chat-App-ScoketIO',
    id: 4,
  },
  {
    title: 'Cash App - Mobile',
    description: "This is a simple wallet app built with React Native and Expo. The app allows users to view their balance, view transaction history, see all the cards the user owns and his contacts.",
    image: '/assets/cashapp.png',
    tags: ['React Native', 'Typescript', 'Expo'],
    visit: 'https://github.com/FranBaca/Cash-App-Mobile',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Entered university & started learning code', },
  { year: 2019, text: 'Started the Henry Bootcamp', },
  { year: 2020, text: 'Got my first job as a developer', },
  { year: 2021, text: 'Got my second job as a developer', },
];